services:
    # web-service
    web:
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: php
            args:
                - APP_ENV=${APP_ENV}
        restart: always
        environment:
            - NODE_VERSION=21.0
            - APP_ENV=${APP_ENV}
        networks:
            - bass
        develop:
            watch:
                - action: sync
                - patch: .
                - target: /var/www
                - ignore:
                      - node_modules
                      - vendor
                      - storage/logs/laravel.log
        volumes:
            - ./storage/logs/laravel.log:/var/www/storage/logs/laravel.log
        ports:
            - 8000:8000
        depends_on:
            - database

    # db-service
    database:
        container_name: database
        image: mysql:8.1
        restart: always
        ports:
            - 3306:3306
        networks:
            - bass
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - bass-sql:/var/lib/mysql

volumes:
    bass-sql:
        driver: local

networks:
    bass:
        driver: bridge
