#!/bin/bash

if [ ! -f ".env" ]; then
  cp .env.example .env
fi

if [ ! -d "vendor" ]; then
  composer install
fi


if [ ! $APP_ENV=="local" ]; then
  echo "Running in production mode"
  php artisan optimize:clear
  php-fpm -D
  nginx -g "daemon off;"
else
  echo "Running in development mode"
  php artisan serve --host=0.0.0.0 --port=8000
fi
