FROM php:7.4 as php

WORKDIR /var/www


# RUN echo "deb http://archive.debian.org/debian/ stretch main \
# deb-src http://archive.debian.org/debian/ stretch main \
# deb http://security.debian.org/debian-security stretch/updates main \
# deb-src http://security.debian.org/debian-security stretch/updates main" > /etc/apt/sources.list


# Install dependencies.
RUN apt-get update && apt-get upgrade -y

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions gd xdebug pdo_mysql mysqli intl


# Copy composer executable.
COPY --from=composer:2.3.5 /usr/bin/composer /usr/bin/composer

# Install Node.js, npm, git
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y git && \
    apt-get install -y nodejs

# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

# RUN export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Copy configuration files.
COPY ./config/php.ini /usr/local/etc/php/php.ini 
COPY ./start-container /usr/local/bin/start-container

RUN chmod +x /usr/local/bin/start-container

EXPOSE 80

ENTRYPOINT ["start-container"]

