FROM php:8.2 as php

WORKDIR /var/www

# Used for prod build.

# Set environment variables
ENV PHP_OPCACHE_ENABLE=0
ENV PHP_OPCACHE_ENABLE_CLI=0
ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
ENV PHP_OPCACHE_REVALIDATE_FREQ=0

# Install dependencies.
RUN apt-get update && apt-get install -y unzip libpq-dev libcurl4-gnutls-dev libonig-dev

# Install PHP extensions.
RUN docker-php-ext-install mysqli pdo pdo_mysql bcmath curl opcache mbstring

# Copy composer executable.
COPY --from=composer:2.3.5 /usr/bin/composer /usr/bin/composer

# Install Node.js, npm, git
RUN curl -sL https://deb.nodesource.com/setup_21.x | bash -
RUN apt-get install -y nodejs \
    && apt-get update \
    && apt-get install -y nodejs \
    && npm install -g npm \
    && npm install git

# Copy configuration files.
COPY ./docker/config/php.ini /usr/local/etc/php/php.ini
# COPY ./docker/config/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf
# COPY ./docker/config/nginx.conf /etc/nginx/nginx.conf

# Copy files from current folder to container current folder (set in workdir).
COPY --chown=www-data:www-data . .

RUN php artisan optimize:clear

# Adjust user permission & group
RUN usermod --uid 1000 www-data
RUN groupmod --gid 1001 www-data

RUN mkdir -p /var/www/storage/framework
RUN mkdir -p /var/www/storage/framework/cache
RUN mkdir -p /var/www/storage/framework/testing
RUN mkdir -p /var/www/storage/framework/sessions
RUN mkdir -p /var/www/storage/framework/views
RUN mkdir -p /var/www/bootstrap/cache

# Fix files ownership.
RUN chown -R www-data /var/www/storage
RUN chown -R www-data /var/www/storage/framework
RUN chown -R www-data /var/www/storage/framework/sessions
RUN chown -R www-data /var/www/bootstrap/cache

# Set correct permission.
RUN chmod -R 755 /var/www/storage
RUN chmod -R 755 /var/www/storage/logs
RUN chmod -R 755 /var/www/storage/framework
RUN chmod -R 755 /var/www/storage/framework/sessions
RUN chmod -R 755 /var/www/bootstrap

EXPOSE 8000

# Run the entrypoint file.
RUN chmod +x ./docker/start-container.sh
ENTRYPOINT ["./docker/start-container.sh"]
